### Site metadata ###

title: Unvolt

# Used if hosting on a custom domain.
url: ""
baseurl: "/unvolt"

### Build settings ###

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

### Content settings ###

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - LICENSE
  - README.md
  - Makefile
